name: Xcode Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode Version (isteğe bağlı)
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Build with xcodebuild
      run: |
        xcodebuild clean build \
        -scheme ToDoApp \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14' \
        CODE_SIGNING_ALLOWED=NO

    - name: Run Tests
      run: |
        xcodebuild test \
        -scheme ToDoApp \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14'
